name: CI/CD Pipeline

on:
    pull_request:
        branches: [ "main" ]
    push:
        branches: [ "main" ]
jobs:
    validate:
        name: "Validate Code and Docker Build"
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            
            - name: Install dependencies for linting and DAG testing
              run: |
                pip install ruff 'apache-airflow==2.9.2'
                pip install -r airflow/requirements.txt
            
            - name: Lint code with ruff
              run: |
                ruff check . 

            - name: Test Airflow DAG Integrity
              env:
                PYTHONPATH: ${{ github.workspace }}/scripts
              run: |
                python -c "from airflow.models.dagbag import DagBag; dag_bag = DagBag('airflow/dags', include_examples=False); assert not dag_bag.import_errors, f'DAG import errors found: {dag_bag.import_errors}'"

            - name: Build Docker images with Docker Compose
              run: |
                docker compose -f docker-compose.yml build 

    build-and-push:
        name: "Build and Push Airflow Image"
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        permissions:
            contents: read
            packages: write
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Airflow image
              uses: docker/build-push-action@v5
              with:
                context: ./airflow
                push: true
                tags: ghcr.io/${{ github.repository_owner }}/data-platform-airflow:latest,ghcr.io/${{ github.repository_owner }}/data-platform-airflow:${{ github.sha }}